---
deployment:
  tasks:
    - export DEPLOYPATH=/home/diahsisk/public_html/
    - /bin/cp -R public/css $DEPLOYPATH
    - /bin/cp -R public/images $DEPLOYPATH
    - /bin/cp -R public/js $DEPLOYPATH
    - /bin/cp -R public/vendor $DEPLOYPATH
    - /bin/cp public/.htaccess $DEPLOYPATH
    - /bin/cp public/favicon.ico $DEPLOYPATH
    - /bin/cp public/index.php $DEPLOYPATH
    - /bin/cp public/robots.txt $DEPLOYPATH
    - /bin/cp public/template.xlsx $DEPLOYPATH
